// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibriwcluceiwpahtnelj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlicml3Y2x1Y2Vpd3BhaHRuZWxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNzY4ODIsImV4cCI6MjA2ODg1Mjg4Mn0.41D43mlXqz0UGG6D8Y_VNWQUxOK0T804orBdR2VF5KM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});